import { SwiperPlugin } from './index';
import { State } from './state/index';
import { Env } from './env/index';
import { SwiperPluginLazyloadPartialOptions } from '../modules/lazyload';
import { SwiperPluginPaginationPartialOptions } from '../modules/pagination';
import { SwiperPluginKeyboardControlPartialOptions } from '../modules/keyboardControl';
import { SwiperPluginNavigationPartialOptions } from '../modules/navigation';
import { SwiperPluginMousewheelPartialOptions } from '../modules/mousewheel';
import { SwiperPluginAutoPlayPartialOptions } from '../modules/autoPlay';
export declare type Direction = 'horizontal' | 'vertical';
export declare type Injections = {
    translate: (state: State, env: Env, options: Options, duration: number) => void;
};
export declare type Options = {
    direction: Direction;
    touchRatio: number;
    touchAngle: number;
    longSwipesRatio: number;
    initialSlide: number;
    loop: boolean;
    freeMode: boolean;
    passiveListeners: boolean;
    resistance: boolean;
    resistanceRatio: number;
    speed: number;
    longSwipesMs: number;
    spaceBetween: number;
    slidesPerView: number;
    centeredSlides: boolean;
    slidePrevClass: string;
    slideNextClass: string;
    slideActiveClass: string;
    slideClass: string;
    wrapperClass: string;
    touchStartPreventDefault: boolean;
    touchStartForcePreventDefault: boolean;
    touchMoveStopPropagation: boolean;
    excludeElements: Array<HTMLElement>;
    isHorizontal: boolean;
    plugins?: Array<SwiperPlugin>;
    injections: Injections;
    lazyload?: SwiperPluginLazyloadPartialOptions;
    mousewheel?: SwiperPluginMousewheelPartialOptions;
    keyboard?: SwiperPluginKeyboardControlPartialOptions;
    navigation?: SwiperPluginNavigationPartialOptions;
    pagination?: SwiperPluginPaginationPartialOptions;
    autoplay?: SwiperPluginAutoPlayPartialOptions;
};
export declare type UserOptions = Partial<Options>;
export declare const defaultOptions: UserOptions;
export declare function optionFormatter(userOptions?: UserOptions): Options;
