import { SwiperPlugin } from './index';
import { State } from './state/index';
import { Env } from './env/index';
import { SwiperPluginLazyloadOptions } from '../modules/lazyload';
import { SwiperPluginPaginationOptions } from '../modules/pagination';
import { SwiperPluginKeyboardControlOptions } from '../modules/keyboardControl';
export declare type Direction = 'horizontal' | 'vertical';
export declare type Injections = {
    translate: (state: State, env: Env, options: Options, duration: number) => void;
};
export declare type Options = {
    direction: Direction;
    touchRatio: number;
    touchAngle: number;
    longSwipesRatio: number;
    initialSlide: number;
    loop: boolean;
    freeMode: boolean;
    mousewheel: boolean;
    passiveListeners: boolean;
    resistance: boolean;
    resistanceRatio: number;
    speed: number;
    longSwipesMs: number;
    spaceBetween: number;
    slidesPerView: number;
    centeredSlides: boolean;
    slidePrevClass: string;
    slideNextClass: string;
    slideActiveClass: string;
    slideClass: string;
    wrapperClass: string;
    touchStartPreventDefault: boolean;
    touchStartForcePreventDefault: boolean;
    touchMoveStopPropagation: boolean;
    excludeElements: Array<HTMLElement>;
    isHorizontal: boolean;
    plugins?: Array<SwiperPlugin>;
    injections: Injections;
    lazyload?: SwiperPluginLazyloadOptions;
    keyboard?: SwiperPluginKeyboardControlOptions;
    pagination?: SwiperPluginPaginationOptions;
};
export declare type UserOptions = Partial<Options>;
export declare function optionFormatter(userOptions: UserOptions): Options;
